# Generated by Django 4.2.25 on 2025-11-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargingrecord',
            name='car_license',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
