# Generated by Django 4.2.25 on 2025-11-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0002_remove_chargingrecord_car_license_delete_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingrecord',
            name='status',
            field=models.CharField(choices=[('completed', 'Unpaid'), ('charging', 'Paid'), ('failed', 'Refunded')], default='charging', max_length=10, verbose_name='Status'),
        ),
    ]
