# Generated by Django 4.2.25 on 2025-11-16 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0003_chargingrecord_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargingrecord',
            name='status',
        ),
    ]
