# Generated by Django 4.2.25 on 2025-11-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging', '0004_remove_chargingrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingrecord',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('in progress', 'In Progress'), ('not started', 'Not Started')], default='not started', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='chargingrecord',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Total Fee (€)'),
        ),
    ]
