# Generated by Django 4.2.25 on 2025-10-25 21:35

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('is_maintenance', models.BooleanField(default=False)),
                ('is_operator', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Device Code')),
                ('charger_type', models.CharField(choices=[('DC', 'Direct Current (Fast)'), ('AC', 'Alternating Current (Slow)')], max_length=2, verbose_name='Charger Type')),
                ('power', models.IntegerField(help_text='e.g. 60kW', verbose_name='Power (kW)')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('charging', 'Charging'), ('fault', 'Faulty'), ('maintenance', 'Maintenance')], default='idle', max_length=20, verbose_name='Status')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='Last Maintenance')),
                ('firmware_version', models.CharField(blank=True, max_length=50, verbose_name='Firmware Version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Installation Date')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Charger',
                'verbose_name_plural': 'Chargers',
                'ordering': ['station__name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Station Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='Operational')),
                ('contact_phone', models.CharField(blank=True, max_length=15, verbose_name='Contact Phone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Charging Station',
                'verbose_name_plural': 'Charging Stations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(verbose_name='Reservation Start')),
                ('end_time', models.DateTimeField(verbose_name='Reservation End')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='charging.charger')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('maintenance_type', models.CharField(choices=[('routine', 'Routine Check'), ('repair', 'Repair'), ('upgrade', 'Firmware Upgrade'), ('replacement', 'Part Replacement')], max_length=20, verbose_name='Type')),
                ('content', models.TextField(verbose_name='Details')),
                ('maintenance_time', models.DateTimeField(verbose_name='Maintenance Time')),
                ('duration', models.IntegerField(help_text='Time spent on maintenance', verbose_name='Duration (minutes)')),
                ('parts_used', models.TextField(blank=True, verbose_name='Parts Used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='charging.charger')),
                ('worker', models.ForeignKey(limit_choices_to={'is_maintenance': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance Record',
                'verbose_name_plural': 'Maintenance Records',
                'ordering': ['-maintenance_time'],
            },
        ),
        migrations.CreateModel(
            name='ChargingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('car_license', models.CharField(max_length=20, verbose_name='License Plate')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Duration (minutes)')),
                ('electricity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Energy (kWh)')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Total Fee (¥)')),
                ('pay_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=10, verbose_name='Payment Status')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='charging.charger')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charging_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Charging Record',
                'verbose_name_plural': 'Charging Records',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddField(
            model_name='charger',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargers', to='charging.station'),
        ),
    ]
